# Default configuration.

## Hugo configuration.
baseURL: 'http://localhost:1313'

title: 'BrtrndB'
languageCode: en-us
theme: 'PaperMod'

mainsections: [ 'posts' ]
pagination:
  pagerSize: 25

buildDrafts: true
buildExpired: true
buildFuture: true
enableEmoji: true
enableInlineShortcodes: true
enableRobotsTXT: true

pygmentsUseClasses: true


minify:
  disableXML: true
  minifyOutput: true

